server:
  port: 8081

spring:
  application:
    name: bung-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mztalk-mysql:3306/bung?serverTimezone=Asia/Seoul
    username: bungservice
    password: bungservice

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true

eureka:
  instance:
    instance-id: bung-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.39.183.175:8761/eureka